TWITTER_KEY: "LCDmmMaGq1ftNPckoOLNA"
TWITTER_SECRET: "DlTar8lAlN8yBbdyRd7V7JkibW0dEfk6jdSJlmQWwo"
OAUTH_TOKEN: "1323028764-uvC7kzAE6SH9k4hNjFA6fTbj8KGfJ94SdCH6WPq"
OAUTH_TOKEN_SECRET: "kiaZU8JJWreKbkWUx7RFzSGXkHHPRhrCnSAumHZdkz8"
